# Uncomment the next line to define a global platform for your project
platform :osx, '10.15'

target 'librawPodDemo' do
#   use_frameworks!

  pod 'libraw', :path => '../', :modular_headers => true
end
